name: CI

on: ["push", "pull_request"]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: yarn

  tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: yarn test --coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  linting:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run linting
        run: yarn lint:eslint
