name: CI

on:
    push:
        branches: [main]
    pull_request:
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install modules
              run: yarn

            - name: Run tests
              run: yarn test --coverage

            - name: Coveralls
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}

    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install modules
              run: yarn

            - name: Run linting
              run: yarn lint:eslint
