name: CI

on: 
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install modules
        run: yarn

      - name: Run tests
        run: yarn test --coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install modules
        run: yarn

      - name: Run linting
        run: yarn lint:eslint
